### ISSUE TITLE
feat: details

### ISSUE THREAD

**Issue by dewita** [jy95/M-moire---Source-Code-un-catalogue-open-source-d-exercices-informatiques#26]
Dans la 4.1, au niveau des fonctionnalités :

- "À titre informatif, le choix du JSON..." sort un peu de nul part. Il faudrait peut-être l'expliquer dès qu'on rencontre le mot JSON pour la première fois :)

- En dessous de la table 4.2, n'oublie pas d'ajouter la référence de ta figure (??)

Partie Solution (frontend)

- Importation des ressources : Qu'est ce que je fais pour le ??? qui concerne la partie backend ? Supprimer ou pas ?

**Comment by jy95** [comment]
- Pour le JSON, l'explication est préventive avant les fonctionnalités pour tuer dans l'oeuf la question du format : il faut d'emblée dire que des détails suivront - les gens étant économes de leur temps ^^
- La référence existait dans le code (\ref{figure:rechercheBibliotheque}) : c'est toi qui l'a viré - faut prévenir avant de virer un truc pareil ^^ D'ailleurs, cela te touche aussi @dewita
![image](https://user-images.githubusercontent.com/9306961/82139012-4d851280-9825-11ea-95c4-cdcf670bf588.png)
![image](https://user-images.githubusercontent.com/9306961/82139020-5544b700-9825-11ea-830d-61fd4c85f6ea.png)
- Pour l'importation, tu fais ce que tu veux : 
  * lien vers la documentation
  * référence au 4.1 et au role based access qui guide pas mal de truc
  * supprimer le ???
